resolver: lts-20.23
packages:
  - .

extra-deps:
  - hashable-1.3.5.0
  - rest-rewrite-0.4.1
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - git: https://github.com/clayrat/liquidhaskell.git
    commit: 8d929d5f6d429915f28c0b24d4737e6c30e18696
    subdirs:
      - .
      - liquidhaskell-boot
      - liquid-prelude
      - liquid-vector
  - git: https://github.com/ucsd-progsys/liquid-fixpoint.git
    commit: a325d750fe8deea98663fe7933516d5d1e683ee1
#- unordered-containers-0.2.19.1@sha256:db11042bb0356c0adea277d0794743829125b4c99455af6af2bd5f7bd5e88a39,3797
allow-newer: true
nix:
  packages: ["z3"]
