resolver: lts-20.26
packages:
  - .

extra-deps:
  - hashable-1.3.5.0
  - rest-rewrite-0.4.1
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - git: https://github.com/clayrat/liquidhaskell.git
    commit: bc08df50b39f1f417a30bc01dcfaf83c252f9415
    subdirs:
      - .
      - liquidhaskell-boot
      - liquid-prelude
      - liquid-vector
  - git: https://github.com/ucsd-progsys/liquid-fixpoint.git
    commit: e4317af546ad388a87f1307e7cdd4984b00020a7
#- unordered-containers-0.2.19.1@sha256:db11042bb0356c0adea277d0794743829125b4c99455af6af2bd5f7bd5e88a39,3797
allow-newer: true
nix:
  packages: ["z3"]
